# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.5
    hooks:
    -   id: sqlfluff-lint
        additional_dependencies: ['dbt-duckdb', 'sqlfluff-templater-dbt']
    -   id: sqlfluff-fix
        additional_dependencies: ['dbt-duckdb', 'sqlfluff-templater-dbt']
