[project]
name = "global-financial-inclusion"
version = "1.0.0"
description = "Pipeline to process the World Bank's Global Findex Database for 2021."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-duckdb>=1.9.0",
]
