Table dim_Respondent {
  wpid_random BIGINT pk
  wgt DOUBLE
  female BIGINT
  age BIGINT
  educ BIGINT
  inc_q BIGINT
  emp_in BIGINT
  urbanicity_f2f BIGINT
}

Table dim_Economy {
  economycode VARCHAR pk
  economy VARCHAR
  regionwb VARCHAR
  pop_adult DOUBLE
}

Table dim_Question {
  question_id BIGINT
  question VARCHAR
}

Table fact_Response {
  respondent_id BIGINT
  economy_id VARCHAR
  question_id BIGINT
  response BIGINT
  year BIGINT
}


Ref: dim_Respondent.wpid_random < fact_Response.respondent_id
Ref: dim_Question.question_id < fact_Response.question_id
Ref: dim_Economy.economycode < fact_Response.economy_id
